site_name: https://gitlab.formbay.com.au/devops/netboot
site_description: netboot.xyz uses iPXE to network boot Operating System installers and utilities from an easy to use menu.
site_author: Rakesh Verma
site_url: https://gitlab.formbay.com.au/devops/netboot
repo_url: https://gitlab.formbay.com.au/devops/netboot
copyright: 
docs_dir: docs
pages:
- Home: 'index.md'
- Boot from...:
    - 'iPXE': 'boot-ipxe.md'
    - 'ISO': 'boot-iso.md'
    - 'TFTP': 'boot-tftp.md'
    - 'USB': 'boot-usb.md'
    - 'Virtual Box': 'boot-vbox.md'
    - 'VMware': 'boot-vmware.md'
- FAQ: 'faq.md'
- Contributing: 'contributing.md'
theme: yeti
